name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OUT_PATH: data/out
      DATA_PATH: data/
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install -r test/requirements.txt
      - name: Static checks
        run: python -m flake8 && python -m mypy src # flake8 settings in [ROOT]/tox.ini
      - name: Test with pytest
        run: python -m pytest -m "not slow"
